/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lidar;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class lidar_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public float angle_min;
    public float angle_max;
    public int range_min;
    public int range_max;
    public int num_ranges;
    public short ranges[];
    public short intensities[];
 
    public lidar_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x01490b20baf5e38dL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lidar.lidar_t.class))
            return 0L;
 
        classes.add(lidar.lidar_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeFloat(this.angle_min); 
 
        outs.writeFloat(this.angle_max); 
 
        outs.writeInt(this.range_min); 
 
        outs.writeInt(this.range_max); 
 
        outs.writeInt(this.num_ranges); 
 
        for (int a = 0; a < this.num_ranges; a++) {
            outs.writeShort(this.ranges[a]); 
        }
 
        for (int a = 0; a < this.num_ranges; a++) {
            outs.writeShort(this.intensities[a]); 
        }
 
    }
 
    public lidar_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public lidar_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lidar.lidar_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lidar.lidar_t o = new lidar.lidar_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.angle_min = ins.readFloat();
 
        this.angle_max = ins.readFloat();
 
        this.range_min = ins.readInt();
 
        this.range_max = ins.readInt();
 
        this.num_ranges = ins.readInt();
 
        this.ranges = new short[(int) num_ranges];
        for (int a = 0; a < this.num_ranges; a++) {
            this.ranges[a] = ins.readShort();
        }
 
        this.intensities = new short[(int) num_ranges];
        for (int a = 0; a < this.num_ranges; a++) {
            this.intensities[a] = ins.readShort();
        }
 
    }
 
    public lidar.lidar_t copy()
    {
        lidar.lidar_t outobj = new lidar.lidar_t();
        outobj.timestamp = this.timestamp;
 
        outobj.angle_min = this.angle_min;
 
        outobj.angle_max = this.angle_max;
 
        outobj.range_min = this.range_min;
 
        outobj.range_max = this.range_max;
 
        outobj.num_ranges = this.num_ranges;
 
        outobj.ranges = new short[(int) num_ranges];
        if (this.num_ranges > 0)
            System.arraycopy(this.ranges, 0, outobj.ranges, 0, this.num_ranges); 
        outobj.intensities = new short[(int) num_ranges];
        if (this.num_ranges > 0)
            System.arraycopy(this.intensities, 0, outobj.intensities, 0, this.num_ranges); 
        return outobj;
    }
 
}

