// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "lcmtypes/lidar_lidar_t.h"

static int __lidar_lidar_t_hash_computed;
static uint64_t __lidar_lidar_t_hash;

uint64_t __lidar_lidar_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __lidar_lidar_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__lidar_lidar_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x01490b20baf5e38dLL
         + __int64_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __lidar_lidar_t_get_hash(void)
{
    if (!__lidar_lidar_t_hash_computed) {
        __lidar_lidar_t_hash = (int64_t)__lidar_lidar_t_hash_recursive(NULL);
        __lidar_lidar_t_hash_computed = 1;
    }

    return __lidar_lidar_t_hash;
}

int __lidar_lidar_t_encode_array(void *buf, int offset, int maxlen, const lidar_lidar_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].angle_min), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].angle_max), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].range_min), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].range_max), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_ranges), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].ranges, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].intensities, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int lidar_lidar_t_encode(void *buf, int offset, int maxlen, const lidar_lidar_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __lidar_lidar_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __lidar_lidar_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __lidar_lidar_t_encoded_array_size(const lidar_lidar_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1);

        size += __float_encoded_array_size(&(p[element].angle_min), 1);

        size += __float_encoded_array_size(&(p[element].angle_max), 1);

        size += __int32_t_encoded_array_size(&(p[element].range_min), 1);

        size += __int32_t_encoded_array_size(&(p[element].range_max), 1);

        size += __int32_t_encoded_array_size(&(p[element].num_ranges), 1);

        size += __int16_t_encoded_array_size(p[element].ranges, p[element].num_ranges);

        size += __int16_t_encoded_array_size(p[element].intensities, p[element].num_ranges);

    }
    return size;
}

int lidar_lidar_t_encoded_size(const lidar_lidar_t *p)
{
    return 8 + __lidar_lidar_t_encoded_array_size(p, 1);
}

int __lidar_lidar_t_decode_array(const void *buf, int offset, int maxlen, lidar_lidar_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].angle_min), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].angle_max), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].range_min), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].range_max), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_ranges), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].ranges = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].ranges, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].intensities = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].num_ranges);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].intensities, p[element].num_ranges);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __lidar_lidar_t_decode_array_cleanup(lidar_lidar_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __float_decode_array_cleanup(&(p[element].angle_min), 1);

        __float_decode_array_cleanup(&(p[element].angle_max), 1);

        __int32_t_decode_array_cleanup(&(p[element].range_min), 1);

        __int32_t_decode_array_cleanup(&(p[element].range_max), 1);

        __int32_t_decode_array_cleanup(&(p[element].num_ranges), 1);

        __int16_t_decode_array_cleanup(p[element].ranges, p[element].num_ranges);
        if (p[element].ranges) free(p[element].ranges);

        __int16_t_decode_array_cleanup(p[element].intensities, p[element].num_ranges);
        if (p[element].intensities) free(p[element].intensities);

    }
    return 0;
}

int lidar_lidar_t_decode(const void *buf, int offset, int maxlen, lidar_lidar_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __lidar_lidar_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __lidar_lidar_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int lidar_lidar_t_decode_cleanup(lidar_lidar_t *p)
{
    return __lidar_lidar_t_decode_array_cleanup(p, 1);
}

int __lidar_lidar_t_clone_array(const lidar_lidar_t *p, lidar_lidar_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __float_clone_array(&(p[element].angle_min), &(q[element].angle_min), 1);

        __float_clone_array(&(p[element].angle_max), &(q[element].angle_max), 1);

        __int32_t_clone_array(&(p[element].range_min), &(q[element].range_min), 1);

        __int32_t_clone_array(&(p[element].range_max), &(q[element].range_max), 1);

        __int32_t_clone_array(&(p[element].num_ranges), &(q[element].num_ranges), 1);

        q[element].ranges = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].ranges, q[element].ranges, p[element].num_ranges);

        q[element].intensities = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].num_ranges);
        __int16_t_clone_array(p[element].intensities, q[element].intensities, p[element].num_ranges);

    }
    return 0;
}

lidar_lidar_t *lidar_lidar_t_copy(const lidar_lidar_t *p)
{
    lidar_lidar_t *q = (lidar_lidar_t*) malloc(sizeof(lidar_lidar_t));
    __lidar_lidar_t_clone_array(p, q, 1);
    return q;
}

void lidar_lidar_t_destroy(lidar_lidar_t *p)
{
    __lidar_lidar_t_decode_array_cleanup(p, 1);
    free(p);
}

int lidar_lidar_t_publish(lcm_t *lc, const char *channel, const lidar_lidar_t *p)
{
      int max_data_size = lidar_lidar_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = lidar_lidar_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _lidar_lidar_t_subscription_t {
    lidar_lidar_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void lidar_lidar_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    lidar_lidar_t p;
    memset(&p, 0, sizeof(lidar_lidar_t));
    status = lidar_lidar_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding lidar_lidar_t!!!\n", status);
        return;
    }

    lidar_lidar_t_subscription_t *h = (lidar_lidar_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    lidar_lidar_t_decode_cleanup (&p);
}

lidar_lidar_t_subscription_t* lidar_lidar_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    lidar_lidar_t_handler_t f, void *userdata)
{
    lidar_lidar_t_subscription_t *n = (lidar_lidar_t_subscription_t*)
                       malloc(sizeof(lidar_lidar_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 lidar_lidar_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg lidar_lidar_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int lidar_lidar_t_subscription_set_queue_capacity (lidar_lidar_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int lidar_lidar_t_unsubscribe(lcm_t *lcm, lidar_lidar_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe lidar_lidar_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

